apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod
  template:
    metadata:
      labels:
        app: prod
    spec:
      containers:
        - image: 'kumgcp/spintest'
          name: prod
          ports:
            - containerPort: 80
