apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    strategy.spinnaker.io/use-source-capacity: 'true'
  name: prod
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: prod
    spec:
      containers:
        - image: 'kumgcp/spintest'
          name: prod
          ports:
            - containerPort: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: prod
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prod
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
